name: 💡 Feature Request
description: Suggest a new feature or enhancement.
title: 'Feature: '
labels: ['enhancement']
body:
  - type: dropdown
    attributes:
      label: Priority
      description: How important is this feature request?
      options:
        - 🔥 Critical
        - 🚨 High
        - 🚧 Medium
        - 💤 Low
  - type: input
    attributes:
      label: Title
      description: Enter a clear and concise description of the feature request.
      placeholder: |
        Enter a clear and concise description of the feature request.
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the feature or enhancement.
      placeholder: |
        Describe the feature or enhancement.
      render: Markdown
  - type: textarea
    attributes:
      label: Additional Information
      description: Share any additional information or context related to the feature request.
      placeholder: |
        Provide any additional information or context.
      render: Markdown
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Describe any alternatives you've considered for this feature request.
      placeholder: |
        Describe any alternatives you've considered.
      render: Markdown
  - type: textarea
    attributes:
      label: Additional Context
      description: Include any other relevant context or screenshots here.
      placeholder: |
        Add any other context or screenshots about the feature request here.
      render: Markdown
