// Auto-generated by `api-gen barrel` — do not edit manually.

export {
  $log,
  getGlobalLogger,
  globalContextStore,
  initGlobalLogger,
  isGlobalLoggerInitialized,
  resetGlobalLogger,
} from "./$log";
export type { AIMetrics } from "./ai";
export { mergeAIMetrics } from "./ai";
export type { LogPreset, PresetConfig } from "./config";
export {
  __resetPresetRegistry,
  getPresetDefaults,
  listPresets,
  registerPreset,
  resolveOptions,
} from "./config";
export type {
  ContextKey,
  RequestContextStore,
  RequestScopedLoggerOptions,
} from "./context";
export {
  createRequestContextStore,
  createRequestScopedLogger,
  loggerStorage,
  mergeLogDataContext,
  useLogger,
} from "./context";
export type { LogixlysiaErrorClass } from "./errors";
export {
  applyErrorLogging,
  errorMap,
  extractErrorFields,
  extractStatus,
  httpError,
  levelForStatus,
} from "./errors";
export { getStatusCode } from "./helpers";
export type {
  ErrorConfig,
  FileConfig,
  FormatConfig,
  LogFilter,
  Logger,
  LogixlysiaConfig,
  LogixlysiaContext,
  LogixlysiaErrorClasses,
  LogixlysiaOptions,
  LogixlysiaStore,
  LogLevel,
  LogRotationConfig,
  Pino,
  PinoConfig,
  RequestIdConfig,
  RequestScopedLogger,
  StartupConfig,
  StoreData,
  Transport,
  TransportsConfig,
} from "./interfaces";
export { HttpError } from "./interfaces";
export type { ResolvedRequestIdConfig } from "./middleware";
export { getOrCreateRequestId, resolveRequestIdConfig } from "./middleware";
export type { TraceContextFields } from "./otel";
export { __resetForTesting, injectTraceContext } from "./otel";
export type { Logixlysia, LogixlysiaSingleton } from "./plugin";
export { createLogPlugin, logixlysia } from "./plugin";
export type { NormalizedLoggedError, StructuredError } from "./utils";
export {
  buildPinoRedactPaths,
  DEFAULT_REDACT_KEYS,
  getRotatedFiles,
  isSensitiveKey,
  isStructuredError,
  normalizeLoggedError,
  pad2,
  pad3,
  parseError,
  parseInterval,
  parseRetention,
  parseSize,
  redact,
  redactRequest,
  redactString,
  sanitizeLogText,
  shouldRotateBySize,
} from "./utils";
export type { WebSocketLike, WsHandlerHooks } from "./websocket";
export { createWsHandlerWrapper } from "./websocket";
