// Auto-generated by `api-gen barrel` — do not edit manually.

export { $log, globalContextStore, initGlobalLogger, isGlobalLoggerInitialized, resetGlobalLogger, getGlobalLogger } from "./$log";
export { mergeAIMetrics } from "./ai";
export type { AIMetrics } from "./ai";
export { registerPreset, getPresetDefaults, listPresets, __resetPresetRegistry, resolveOptions } from "./config";
export type { PresetConfig, LogPreset } from "./config";
export { createRequestContextStore, mergeLogDataContext, loggerStorage, useLogger, createRequestScopedLogger } from "./context";
export type { ContextKey, RequestContextStore, RequestScopedLoggerOptions } from "./context";
export { levelForStatus, extractStatus, extractErrorFields, applyErrorLogging, errorMap, httpError } from "./errors";
export type { LogixlysiaErrorClass } from "./errors";
export { getStatusCode } from "./helpers";
export { HttpError } from "./interfaces";
export type { Pino, LogLevel, StoreData, LogixlysiaStore, Transport, LogRotationConfig, RequestIdConfig, LogFilter, PinoConfig, StartupConfig, FormatConfig, FileConfig, TransportsConfig, ErrorConfig, LogixlysiaErrorClasses, LogixlysiaConfig, LogixlysiaOptions, Logger, RequestScopedLogger, LogixlysiaContext } from "./interfaces";
export { resolveRequestIdConfig, getOrCreateRequestId } from "./middleware";
export type { ResolvedRequestIdConfig } from "./middleware";
export { injectTraceContext, __resetForTesting } from "./otel";
export type { TraceContextFields } from "./otel";
export { createLogPlugin, logixlysia } from "./plugin";
export type { LogixlysiaSingleton, Logixlysia } from "./plugin";
export { parseError, isStructuredError, normalizeLoggedError, pad2, pad3, DEFAULT_REDACT_KEYS, isSensitiveKey, buildPinoRedactPaths, redactString, redact, redactRequest, parseSize, parseInterval, parseRetention, shouldRotateBySize, getRotatedFiles, sanitizeLogText } from "./utils";
export type { StructuredError, NormalizedLoggedError } from "./utils";
export { createWsHandlerWrapper } from "./websocket";
export type { WebSocketLike, WsHandlerHooks } from "./websocket";
