name: 🤖 Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 🛫 Checkout Code
        uses: actions/checkout@v6
      - name: 🔄 Install gh-aw extension
        uses: github/gh-aw/actions/setup-cli@b5a9fb08751b738a86b3b605ff1fdf34956adbf4 # v0.65.4
        with:
          version: v0.55.0
