name: 🧑‍🏫 Dependency Review

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout Code
        uses: actions/checkout@v7
      - name: ✒️ Dependency Review
        uses: actions/dependency-review-action@v5
