name: 🤖 Automatic Labeler

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: 🔖 Label Issues and Pull Requests
    runs-on: ubuntu-latest
    steps:
      - name: 🔖 Add Labels
        uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
      - name: 😵 Check Conflicts
        uses: mschilde/auto-label-merge-conflicts@3fdaf1c8b3f8e5b0f88753d9cb3c9c779370b3ef # master
        with:
          CONFLICT_LABEL_NAME: "conflict"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
